### ISSUE TITLE
Angles in Vector

### ISSUE THREAD

**Issue by marcelobianchi** [endarthur/autti#9]
While reviewing the Vector methods it looks like that some methods ask for angles in degrees other in radians. Also, some methods returns values in radians. 

It is necessary to make an uniform decision about that.

**Comment by endarthur** [comment]
A uniform decision would mean that angles would be all degrees or all radians? Or would it be OK if, for example, all attitudes (which would also mean global plot rotation, as they are an azimuth, plunge and rake tuple) in degrees, and all other angles in radians?

**Comment by marcelobianchi** [comment]
Uniform is mostly clear. But I do agree that attitudes should be in degrees
for sake of usability.

We should also normally think also on the reuse of the methods inside the
interface. For example, the Vector.angle() method returns in radians(). If
this value returned is used at the great_circle() directly would be
problematic, but this is the most clear case for me that a value that is
not a attitude in expected in degrees. But for sure leaving the angle() in
radians sounds better.

This way we would end-up in a mix of units, leaving attitudes in degrees
and others in radians. Do you remember some more points were the units can
be confusing ?

**Comment by endarthur** [comment]
I haven't thought about the step parameter in great circle (and small circle), and I guess that it should be really in radians. small_circle's alpha is in radians, so as in the example jupyter notebook, you can pass it the result of angle. Leaving step as input in degrees was really oversight, I'll change it now.

Passing scalar angles in degrees instead of radians sounds wrong, I think.

In the end, attitudes => degrees, angles => radians is a mix of units, but it seems more usable in the long run.

**Comment by marcelobianchi** [comment]
Looks like ok now. As we go we keep this in mind.
